with open('pyproject.toml', 'w') as f:
    f.write('[build-system]\n')
    f.write('requires = ["setuptools"]\n')
    f.write('build-backend = "setuptools.backends.legacy:build"\n')
    f.write('\n')
    f.write('[project]\n')
    f.write('name = "ticketmind-openenv"\n')
    f.write('version = "1.0.0"\n')
    f.write('description = "TicketMind OpenEnv"\n')
    f.write('requires-python = ">=3.10"\n')
    f.write('dependencies = [\n')
    f.write('    "fastapi>=0.110.0",\n')
    f.write('    "uvicorn>=0.29.0",\n')
    f.write('    "pydantic>=2.0.0",\n')
    f.write('    "requests>=2.31.0",\n')
    f.write('    "openai>=1.12.0",\n')
    f.write(']\n')
print('Done')